-- MySQL Script generated by MySQL Workbench
-- Sun Dec  1 22:40:01 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Bloomware
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Bloomware` ;

-- -----------------------------------------------------
-- Schema Bloomware
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Bloomware` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
SHOW WARNINGS;
USE `Bloomware` ;

-- -----------------------------------------------------
-- Table `Administrador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Administrador` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Administrador` (
  `ID_Administrador` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellidos` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Telefono` VARCHAR(45) NOT NULL,
  `Contraseña` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_Administrador`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cliente` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Cliente` (
  `ID_Cliente` INT NOT NULL,
  `ID_Producto` VARCHAR(45) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellidos` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Telefono` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_Cliente`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Empleado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Empleado` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Empleado` (
  `ID_Empleado` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellidos` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Telefono` VARCHAR(45) NOT NULL,
  `Cargo` VARCHAR(45) NOT NULL,
  `Contraseña` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_Empleado`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Gestionar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Gestionar` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Gestionar` (
  `Producto_ID_Producto` INT NOT NULL,
  `Cliente_ID_Cliente` INT NOT NULL,
  PRIMARY KEY (`Producto_ID_Producto`, `Cliente_ID_Cliente`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Producto` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Producto` (
  `ID_Producto` INT NOT NULL AUTO_INCREMENT,
  `Nombre_Producto` VARCHAR(45) BINARY NOT NULL,
  `Cantidad` INT NOT NULL,
  `Precio` INT NOT NULL,
  `Categoria` VARCHAR(45) NOT NULL,
  `Lote` INT NOT NULL,
  `Fecha_Vencimiento` DATE NOT NULL,
  `Administrador_ID_Administrador` INT NOT NULL,
  PRIMARY KEY (`ID_Producto`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Proveedores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Proveedores` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Proveedores` (
  `Nit_Proveedor` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Direccion` VARCHAR(60) NOT NULL,
  `Telefono` VARCHAR(45) NOT NULL,
  `Categoria` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Nit_Proveedor`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Realizacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Realizacion` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Realizacion` (
  `Reporte_ID_Reporte` INT NOT NULL,
  `Empleado_ID_Empleado` INT NOT NULL,
  `Fecha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Reporte_ID_Reporte`, `Empleado_ID_Empleado`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Reporte`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Reporte` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Reporte` (
  `ID_Reporte` INT NOT NULL AUTO_INCREMENT,
  `Fecha y hora` DATE NOT NULL,
  `ID_Clientes` VARCHAR(45) NOT NULL,
  `ID_Productos` VARCHAR(45) NOT NULL,
  `ID_Usuario` VARCHAR(45) NOT NULL,
  `Nit_Proveedor` VARCHAR(45) NOT NULL,
  `Administrador_ID_Administrador` INT NOT NULL,
  PRIMARY KEY (`ID_Reporte`, `Administrador_ID_Administrador`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Suministra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Suministra` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Suministra` (
  `Producto_ID_Producto` INT NOT NULL,
  `Proveedores_Nit_Proveedor` INT NOT NULL,
  PRIMARY KEY (`Producto_ID_Producto`, `Proveedores_Nit_Proveedor`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Usuario` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Usuario` (
  `ID_Usuario` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Telefono` VARCHAR(45) NOT NULL,
  `Contraseña` VARCHAR(45) NOT NULL,
  `Administrador_ID_Administrador` INT NOT NULL,
  PRIMARY KEY (`ID_Usuario`, `Administrador_ID_Administrador`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Vende`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Vende` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Vende` (
  `Empleado_ID_Empleado` INT NOT NULL,
  `Producto_ID_Producto` INT NOT NULL,
  PRIMARY KEY (`Empleado_ID_Empleado`, `Producto_ID_Producto`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
